### ISSUE TITLE
no insider builds support

### ISSUE THREAD

**Issue by nin52** [InvoxiPlayGames/FestivalInstrumentMapper#20]
I know its in the readme but damn, so close yet so far...

**Comment by Untaxed1518** [comment]
I fixed it by grabbing the xboxgipsynthetic.dll (about 128kb in size) from my friend's PC and putting it in the same folder as FestivalInstrumentMapper :]

**Comment by nin52** [comment]
> [Untaxed1518](/Untaxed1518)

really...? i tried downloading the dll file online but i still cant get it to work :(

**Comment by TheNathannator** [comment]
> i tried downloading the dll file online

Please don't just download random files off of the internet, you're taking a very big risk in doing that.

**Comment by nin52** [comment]
> > i tried downloading the dll file online
> 
> Please don't just download random files off of the internet, you're taking a very big risk in doing that.

At this point I'm trying everything, pretty annoyed that I keep getting that error :[

**Comment by Untaxed1518** [comment]
> Please don't just download random files off of the internet, you're taking a very big risk in doing that.

Hence me grabbing the file from a trusted friend, please don't download random DLLs...
